version: 2.1

jobs:
    unit-and-integration-tests:
        docker:
            - image: node:18.17.0-slim
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: pnpm install
            - run:
                  name: unit-and-integration-tests
                  command: pnpm run test:ci

    ai-e2e-tests:
        docker:
            - image: node:18.17.0-slim
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: pnpm install
            - run:
                  name: ai-e2e-tests
                  command: pnpm run ai-e2e-test:ci

workflows:
    version: 2
    all_tests:
        jobs:
            - unit-and-integration-tests
            - ai-e2e-tests
